version: '3.8'

services:
    database:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=passwd
        ports:
            - 5432:5432
        volumes:
            - ./db_data:/var/lib/postgresql/data
